apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: verb-api-container
          image: aggregator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002