apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: app
spec:
  selector: 
    app: aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30082  # Exposes the service externally on this port

  type: LoadBalancer
