apiVersion: v1
kind: Service
metadata:
  name: verbs-service
  namespace: app
spec:
  selector:
    app: verbs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # Exposes the service externally on this port

  type: LoadBalancer
