apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app
spec:
  selector:
    app: web  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 80     # Port the container is listening on
  type: LoadBalancer  # Expose it externally using a load balancer (use ClusterIP for internal access only)
