apiVersion: v1
kind: Service
metadata:
  name: nouns-service
  namespace: app
spec:
  selector: 
    app: nouns
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

  type: LoadBalancer
